#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# STOP WEBMIN
#=================================================
ynh_script_progression --message="Stopping Webmin service..." --weight=1

# Remove the dedicated Webmin
ynh_systemd_action --service_name=$app --action=stop

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=3

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# SPECIFIC REMOVE
#=================================================

ynh_remove_app_dependencies $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of WebMin completed" --last
